export enum CountryCode {
  ALL = "ALL", // All countries
  AW = "AW", // Aruba
  AF = "AF", // Afghanistan
  AO = "AO", // Angola
  AI = "AI", // Anguilla
  AX = "AX", // Åland Islands
  AL = "AL", // Albania
  AD = "AD", // Andorra
  AE = "AE", // United Arab Emirates
  AR = "AR", // Argentina
  AM = "AM", // Armenia
  AS = "AS", // American Samoa
  AQ = "AQ", // Antarctica
  TF = "TF", // French Southern Territories
  AG = "AG", // Antigua and Barbuda
  AU = "AU", // Australia
  AT = "AT", // Austria
  AZ = "AZ", // Azerbaijan
  BI = "BI", // Burundi
  BE = "BE", // Belgium
  BJ = "BJ", // Benin
  BQ = "BQ", // Bonaire, Sint Eustatius and Saba
  BF = "BF", // Burkina Faso
  BD = "BD", // Bangladesh
  BG = "BG", // Bulgaria
  BH = "BH", // Bahrain
  BS = "BS", // Bahamas
  BA = "BA", // Bosnia and Herzegovina
  BL = "BL", // Saint Barthélemy
  BY = "BY", // Belarus
  BZ = "BZ", // Belize
  BM = "BM", // Bermuda
  BO = "BO", // Bolivia, Plurinational State of
  BR = "BR", // Brazil
  BB = "BB", // Barbados
  BN = "BN", // Brunei Darussalam
  BT = "BT", // Bhutan
  BV = "BV", // Bouvet Island
  BW = "BW", // Botswana
  CF = "CF", // Central African Republic
  CA = "CA", // Canada
  CC = "CC", // Cocos (Keeling) Islands
  CH = "CH", // Switzerland
  CL = "CL", // Chile
  CN = "CN", // China
  CI = "CI", // Côte d'Ivoire
  CM = "CM", // Cameroon
  CD = "CD", // Congo, The Democratic Republic of the
  CG = "CG", // Congo
  CK = "CK", // Cook Islands
  CO = "CO", // Colombia
  KM = "KM", // Comoros
  CV = "CV", // Cabo Verde
  CR = "CR", // Costa Rica
  CU = "CU", // Cuba
  CW = "CW", // Curaçao
  CX = "CX", // Christmas Island
  KY = "KY", // Cayman Islands
  CY = "CY", // Cyprus
  CZ = "CZ", // Czechia
  DE = "DE", // Germany
  DJ = "DJ", // Djibouti
  DM = "DM", // Dominica
  DK = "DK", // Denmark
  DO = "DO", // Dominican Republic
  DZ = "DZ", // Algeria
  EC = "EC", // Ecuador
  EG = "EG", // Egypt
  ER = "ER", // Eritrea
  EH = "EH", // Western Sahara
  ES = "ES", // Spain
  EE = "EE", // Estonia
  ET = "ET", // Ethiopia
  FI = "FI", // Finland
  FJ = "FJ", // Fiji
  FK = "FK", // Falkland Islands (Malvinas)
  FR = "FR", // France
  FO = "FO", // Faroe Islands
  FM = "FM", // Micronesia, Federated States of
  GA = "GA", // Gabon
  GB = "GB", // United Kingdom
  GE = "GE", // Georgia
  GG = "GG", // Guernsey
  GH = "GH", // Ghana
  GI = "GI", // Gibraltar
  GN = "GN", // Guinea
  GP = "GP", // Guadeloupe
  GM = "GM", // Gambia
  GW = "GW", // Guinea-Bissau
  GQ = "GQ", // Equatorial Guinea
  GR = "GR", // Greece
  GD = "GD", // Grenada
  GL = "GL", // Greenland
  GT = "GT", // Guatemala
  GF = "GF", // French Guiana
  GU = "GU", // Guam
  GY = "GY", // Guyana
  HK = "HK", // Hong Kong
  HM = "HM", // Heard Island and McDonald Islands
  HN = "HN", // Honduras
  HR = "HR", // Croatia
  HT = "HT", // Haiti
  HU = "HU", // Hungary
  ID = "ID", // Indonesia
  IM = "IM", // Isle of Man
  IN = "IN", // India
  IO = "IO", // British Indian Ocean Territory
  IE = "IE", // Ireland
  IR = "IR", // Iran, Islamic Republic of
  IQ = "IQ", // Iraq
  IS = "IS", // Iceland
  IL = "IL", // Israel
  IT = "IT", // Italy
  JM = "JM", // Jamaica
  JE = "JE", // Jersey
  JO = "JO", // Jordan
  JP = "JP", // Japan
  KZ = "KZ", // Kazakhstan
  KE = "KE", // Kenya
  KG = "KG", // Kyrgyzstan
  KH = "KH", // Cambodia
  KI = "KI", // Kiribati
  KN = "KN", // Saint Kitts and Nevis
  KR = "KR", // Korea, Republic of
  KW = "KW", // Kuwait
  LA = "LA", // Lao People's Democratic Republic
  LB = "LB", // Lebanon
  LR = "LR", // Liberia
  LY = "LY", // Libya
  LC = "LC", // Saint Lucia
  LI = "LI", // Liechtenstein
  LK = "LK", // Sri Lanka
  LS = "LS", // Lesotho
  LT = "LT", // Lithuania
  LU = "LU", // Luxembourg
  LV = "LV", // Latvia
  MO = "MO", // Macao
  MF = "MF", // Saint Martin (French part)
  MA = "MA", // Morocco
  MC = "MC", // Monaco
  MD = "MD", // Moldova, Republic of
  MG = "MG", // Madagascar
  MV = "MV", // Maldives
  MX = "MX", // Mexico
  MH = "MH", // Marshall Islands
  MK = "MK", // North Macedonia
  ML = "ML", // Mali
  MT = "MT", // Malta
  MM = "MM", // Myanmar
  ME = "ME", // Montenegro
  MN = "MN", // Mongolia
  MP = "MP", // Northern Mariana Islands
  MZ = "MZ", // Mozambique
  MR = "MR", // Mauritania
  MS = "MS", // Montserrat
  MQ = "MQ", // Martinique
  MU = "MU", // Mauritius
  MW = "MW", // Malawi
  MY = "MY", // Malaysia
  YT = "YT", // Mayotte
  NA = "NA", // Namibia
  NC = "NC", // New Caledonia
  NE = "NE", // Niger
  NF = "NF", // Norfolk Island
  NG = "NG", // Nigeria
  NI = "NI", // Nicaragua
  NU = "NU", // Niue
  NL = "NL", // Netherlands
  NO = "NO", // Norway
  NP = "NP", // Nepal
  NR = "NR", // Nauru
  NZ = "NZ", // New Zealand
  OM = "OM", // Oman
  PK = "PK", // Pakistan
  PA = "PA", // Panama
  PN = "PN", // Pitcairn
  PE = "PE", // Peru
  PH = "PH", // Philippines
  PW = "PW", // Palau
  PG = "PG", // Papua New Guinea
  PL = "PL", // Poland
  PR = "PR", // Puerto Rico
  KP = "KP", // Korea, Democratic People's Republic of
  PT = "PT", // Portugal
  PY = "PY", // Paraguay
  PS = "PS", // Palestine, State of
  PF = "PF", // French Polynesia
  QA = "QA", // Qatar
  RE = "RE", // Réunion
  RO = "RO", // Romania
  RU = "RU", // Russian Federation
  RW = "RW", // Rwanda
  SA = "SA", // Saudi Arabia
  SD = "SD", // Sudan
  SN = "SN", // Senegal
  SG = "SG", // Singapore
  GS = "GS", // South Georgia and the South Sandwich Islands
  SH = "SH", // Saint Helena, Ascension and Tristan da Cunha
  SJ = "SJ", // Svalbard and Jan Mayen
  SB = "SB", // Solomon Islands
  SL = "SL", // Sierra Leone
  SV = "SV", // El Salvador
  SM = "SM", // San Marino
  SO = "SO", // Somalia
  PM = "PM", // Saint Pierre and Miquelon
  RS = "RS", // Serbia
  SS = "SS", // South Sudan
  ST = "ST", // Sao Tome and Principe
  SR = "SR", // Suriname
  SK = "SK", // Slovakia
  SI = "SI", // Slovenia
  SE = "SE", // Sweden
  SZ = "SZ", // Eswatini
  SX = "SX", // Sint Maarten (Dutch part)
  SC = "SC", // Seychelles
  SY = "SY", // Syrian Arab Republic
  TC = "TC", // Turks and Caicos Islands
  TD = "TD", // Chad
  TG = "TG", // Togo
  TH = "TH", // Thailand
  TJ = "TJ", // Tajikistan
  TK = "TK", // Tokelau
  TM = "TM", // Turkmenistan
  TL = "TL", // Timor-Leste
  TO = "TO", // Tonga
  TT = "TT", // Trinidad and Tobago
  TN = "TN", // Tunisia
  TR = "TR", // Turkey
  TV = "TV", // Tuvalu
  TW = "TW", // Taiwan, Province of China
  TZ = "TZ", // Tanzania, United Republic of
  UG = "UG", // Uganda
  UA = "UA", // Ukraine
  UM = "UM", // United States Minor Outlying Islands
  UY = "UY", // Uruguay
  US = "US", // United States
  UZ = "UZ", // Uzbekistan
  VA = "VA", // Holy See (Vatican City State)
  VC = "VC", // Saint Vincent and the Grenadines
  VE = "VE", // Venezuela, Bolivarian Republic of
  VG = "VG", // Virgin Islands, British
  VI = "VI", // Virgin Islands, U.S.
  VN = "VN", // Viet Nam
  VU = "VU", // Vanuatu
  WF = "WF", // Wallis and Futuna
  WS = "WS", // Samoa
  YE = "YE", // Yemen
  ZA = "ZA", // South Africa
  ZM = "ZM", // Zambia
  ZW = "ZW", // Zimbabwe
}