export enum EmailTemplate {
  VERIFY_EMAIL = "VERIFY_EMAIL",
  RESET_PASSWORD = "RESET_PASSWORD",
  PLAN_END_AFTER_FIVE_DAYS = "PLAN_END_AFTER_FIVE_DAYS",
  PLAN_END_AFTER_ONE_DAY = "PLAN_END_AFTER_ONE_DAY",
  PLAN_ENDED = "PLAN_ENDED",
}
