export const SKIPPED_FILENAMES = [
  'auth.js',
  'main.js',
  'main_scripts.js',
  'axios.min.js',
  'bean-script.js',
  'app.js',
  'script.js',
  'loadBuffer.js',
];

export const BLACKLISTED_DOMAINS = [
  'afrdtech.com',
  'priallysearly.com',
  'clarity.ms',
  'retoricamanual.com',
  'lerandbigdicker.com',
  'metrica.yandex.ru',
  'metrica.yandex.com',
  'mc.yandex.ru',
  'hotjar.com',
  'kaminari.space',
  'kaminari.systems',
  'kaminari.click',
  'knowyourbot.com',
  'aaakmnr.com',
  'afr-d.com',
  'click-trade.icu',
];

export const BLACKLISTED_SCRIPTS = [
  'integration/jquery.validate.min.js',
  'integration/intlTelInputWithUtils.min.js',
  'integration/scripts.js',
  'integration/jquery.min.js',
  'bean-script.js',
  'app.js',
  'script.js',
];

export const BLACKLISTED_PARAMS = ['fraud', 'subld', 'kmnrKey', 'kaminari'];

export const UBLOCK_RAW_RULES = [
  '||*/lander/bean-script.js^',
  '||metrica.yandex.ru^',
  '||metrica.yandex.com^',
  '||mc.yandex.ru^',
  '||mc.webvisor.org^',
  '||lerandbigdicker.com^',
  '||retoricamanual.com^',
  '||clarity.ms^',
  '||priallysearly.com^',
  '||hotjar.com^',
  '||afrdtech.com^',
  '||kaminari.space^',
  '||kaminari.systems^',
  '||kaminari.click^',
  '||knowyourbot.com^',
  '||aaakmnr.com^',
  '||afr-d.com^',
  '||click-trade.icu^',
  '||*/integration/jquery.validate.min.js^',
  '||*/integration/scripts.js^',
  '||*/integration/jquery.min.js^',
  '||*/../integration/jquery.validate.min.js^',
  '||*/../integration/intlTelInputWithUtils.min.js^',
  '||*/../integration/scripts.js^',
  '||*/../integration/jquery.min.js^',
  '||*/integration/^',
  '||*/../integration/^',
  '||*/bean-script.js^',
  '||*/../bean-script.js^',
  '/bean-script.js^',
  '||*kmnrKey*^',
  '||*_update_tokens*^',
  '||*/script.js^',
  '||*/app.js^',
];