import { MobileViewport } from '@interfaces';

// 13.05.2025
// https://yesviz.com/viewport/
// =============================================================
// SCRIPT TO EXTRACT VIEWPORTS FROM YESVIZ
// =============================================================
// const rows = document.querySelectorAll('table tr');
// const viewports = [];

// rows.forEach(row => {
//   const cells = row.querySelectorAll('td');
//   if (cells.length >= 7) {
//     const type = cells[0].innerText.trim();
//     const name = cells[1].innerText.trim();
//     const [width, height] = cells[2].innerText.trim().split(' x ').map(Number);
//     const pixelRatio = parseFloat(cells[5].innerText.trim());
//     const screenSize = parseFloat(cells[4].innerText.trim());
//     const densityPPI = parseInt(cells[6].innerText.trim(), 10);

//     viewports.push({
//       name,
//       width,
//       height,
//       deviceScaleFactor: pixelRatio,
//       isMobile: type.toLowerCase() === 'mobile',
//       hasTouch: type.toLowerCase() !== 'laptop',
//       screenSize,
//       densityPPI
//     });
//   }
// });

// console.log(JSON.stringify(viewports, null, 2));

export const MOBILE_VIEWPORTS: MobileViewport[] = [
  {
    name: 'Apple iPad 10.2"',
    width: 810,
    height: 1080,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 10.2,
    densityPPI: 264,
  },
  {
    name: 'Apple iPad Air',
    width: 834,
    height: 1112,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 10.5,
    densityPPI: 264,
  },
  {
    name: 'Apple iPad Air (2020)',
    width: 820,
    height: 1180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 10.9,
    densityPPI: 264,
  },
  {
    name: 'Apple iPad Mini',
    width: 768,
    height: 1024,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 7.9,
    densityPPI: 324,
  },
  {
    name: 'Apple iPad Pro 11"',
    width: 834,
    height: 1194,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 11,
    densityPPI: 264,
  },
  {
    name: 'Apple iPad Pro 12.9"',
    width: 1024,
    height: 1366,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 12.9,
    densityPPI: 264,
  },
  {
    name: 'Apple iPhone 11',
    width: 414,
    height: 896,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 11 Pro',
    width: 375,
    height: 812,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.8,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone 11 Pro Max',
    width: 414,
    height: 896,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone 12',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 12 mini',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.4,
    densityPPI: 476,
  },
  {
    name: 'Apple iPhone 12 Pro',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 12 Pro Max',
    width: 428,
    height: 926,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone 13',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 13 mini',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.4,
    densityPPI: 476,
  },
  {
    name: 'Apple iPhone 13 Pro',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 13 Pro Max',
    width: 428,
    height: 926,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone 14',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 14 Plus',
    width: 428,
    height: 926,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone 14 Pro',
    width: 393,
    height: 852,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 14 Pro Max',
    width: 430,
    height: 932,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 15',
    width: 393,
    height: 852,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 461,
  },
  {
    name: 'Apple iPhone 15 Plus',
    width: 430,
    height: 932,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 15 Pro',
    width: 393,
    height: 852,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 461,
  },
  {
    name: 'Apple iPhone 15 Pro Max',
    width: 430,
    height: 932,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 16',
    width: 393,
    height: 852,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 16 Plus',
    width: 430,
    height: 932,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 16 Pro',
    width: 402,
    height: 874,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 16 Pro Max',
    width: 440,
    height: 956,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.9,
    densityPPI: 460,
  },
  {
    name: 'Apple iPhone 5',
    width: 320,
    height: 568,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 5c',
    width: 320,
    height: 568,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 5s',
    width: 320,
    height: 568,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 6',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 6s',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 6s Plus',
    width: 414,
    height: 736,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 401,
  },
  {
    name: 'Apple iPhone 7',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 7 Plus',
    width: 414,
    height: 736,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 401,
  },
  {
    name: 'Apple iPhone 8',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone 8 Plus',
    width: 414,
    height: 736,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 401,
  },
  {
    name: 'Apple iPhone SE',
    width: 320,
    height: 568,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone SE (2020)',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone SE (2022)',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone X',
    width: 375,
    height: 812,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.8,
    densityPPI: 458,
  },
  {
    name: 'Apple iPhone XR',
    width: 414,
    height: 896,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 326,
  },
  {
    name: 'Apple iPhone XS Max',
    width: 414,
    height: 896,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 458,
  },
  {
    name: 'Apple Watch Series (40mm)',
    width: 197,
    height: 162,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.57,
    densityPPI: 326,
  },
  {
    name: 'Apple Watch Series (44mm)',
    width: 224,
    height: 184,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.78,
    densityPPI: 326,
  },
  {
    name: 'Blackberry Classic',
    width: 390,
    height: 390,
    deviceScaleFactor: 1.85,
    isMobile: true,
    hasTouch: true,
    screenSize: 3.5,
    densityPPI: 294,
  },
  {
    name: 'BlackBerry Keyone',
    width: 360,
    height: 540,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.5,
    densityPPI: 434,
  },
  {
    name: 'Blackberry Leap',
    width: 390,
    height: 695,
    deviceScaleFactor: 1.85,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 294,
  },
  {
    name: 'Blackberry Passport',
    width: 504,
    height: 504,
    deviceScaleFactor: 2.85,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.5,
    densityPPI: 453,
  },
  {
    name: 'BlackBerry Priv',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.4,
    densityPPI: 540,
  },
  {
    name: 'Blackberry Q10',
    width: 346,
    height: 346,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 3.1,
    densityPPI: 328,
  },
  {
    name: 'Blackberry Z10',
    width: 384,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.2,
    densityPPI: 355,
  },
  {
    name: 'Blackberry Z30',
    width: 360,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 294,
  },
  {
    name: 'Google Pixel',
    width: 412,
    height: 732,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'Google Pixel 2',
    width: 412,
    height: 732,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'Google Pixel 2 XL',
    width: 412,
    height: 823,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 538,
  },
  {
    name: 'Google Pixel 3',
    width: 393,
    height: 786,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 443,
  },
  {
    name: 'Google Pixel 3 XL',
    width: 412,
    height: 846,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 523,
  },
  {
    name: 'Google Pixel 3a',
    width: 393,
    height: 808,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.6,
    densityPPI: 441,
  },
  {
    name: 'Google Pixel 3a XL',
    width: 412,
    height: 823,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 402,
  },
  {
    name: 'Google Pixel 4',
    width: 393,
    height: 830,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 444,
  },
  {
    name: 'Google Pixel 4 XL',
    width: 412,
    height: 869,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 537,
  },
  {
    name: 'Google Pixel 4a',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.81,
    densityPPI: 443,
  },
  {
    name: 'Google Pixel 5',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 432,
  },
  {
    name: 'Google Pixel XL',
    width: 412,
    height: 732,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 534,
  },
  {
    name: 'Honor 6X',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 403,
  },
  {
    name: 'Honor 7X',
    width: 360,
    height: 720,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.93,
    densityPPI: 407,
  },
  {
    name: 'Honor 8X',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 397,
  },
  {
    name: 'Honor 9X',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.59,
    densityPPI: 391,
  },
  {
    name: 'HTC Desire 19s',
    width: 360,
    height: 760,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 271,
  },
  {
    name: 'HTC One',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.7,
    densityPPI: 469,
  },
  {
    name: 'HTC One M8',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'HTC One M9',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'HTC U Ultra',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 513,
  },
  {
    name: 'HTC U11',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 534,
  },
  {
    name: 'HTC U11+',
    width: 360,
    height: 720,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 537,
  },
  {
    name: 'HTC U12+',
    width: 360,
    height: 720,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 537,
  },
  {
    name: 'HTC Wildfire X',
    width: 360,
    height: 760,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 271,
  },
  {
    name: 'Huawei Mate 10 Lite',
    width: 360,
    height: 720,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.9,
    densityPPI: 409,
  },
  {
    name: 'Huawei Mate 20 Lite',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 409,
  },
  {
    name: 'Huawei Mate 20 Pro',
    width: 360,
    height: 780,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.39,
    densityPPI: 538,
  },
  {
    name: 'Huawei Mate 30',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.62,
    densityPPI: 389,
  },
  {
    name: 'Huawei Mate 30 Pro',
    width: 392,
    height: 800,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.53,
    densityPPI: 409,
  },
  {
    name: 'Huawei MatePad Pro',
    width: 1280,
    height: 800,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 10.8,
    densityPPI: 280,
  },
  {
    name: 'Huawei Nova 6',
    width: 360,
    height: 800,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.57,
    densityPPI: 401,
  },
  {
    name: 'Huawei Nova 7 Pro',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.57,
    densityPPI: 392,
  },
  {
    name: 'Huawei Nova 7 SE',
    width: 360,
    height: 800,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 405,
  },
  {
    name: 'Huawei Nova 7i',
    width: 360,
    height: 770,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 398,
  },
  {
    name: 'Huawei P10 Plus',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 540,
  },
  {
    name: 'Huawei P20 lite',
    width: 360,
    height: 760,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.84,
    densityPPI: 432,
  },
  {
    name: 'Huawei P20 Pro',
    width: 360,
    height: 747,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 408,
  },
  {
    name: 'Huawei P30',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 422,
  },
  {
    name: 'Huawei P30 Lite',
    width: 360,
    height: 771,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.15,
    densityPPI: 415,
  },
  {
    name: 'Huawei P30 Pro',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.47,
    densityPPI: 398,
  },
  {
    name: 'Huawei P40',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 422,
  },
  {
    name: 'Huawei P40 Lite',
    width: 360,
    height: 770,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 398,
  },
  {
    name: 'Huawei P40 Pro',
    width: 400,
    height: 880,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.58,
    densityPPI: 441,
  },
  {
    name: 'Huawei P8 Lite (2017)',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 424,
  },
  {
    name: 'Huawei P9, P9 Lite',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 424,
  },
  {
    name: 'Huawei Watch GT',
    width: 227,
    height: 227,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.39,
    densityPPI: 326,
  },
  {
    name: 'Huawei Y9 Prime',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.59,
    densityPPI: 391,
  },
  {
    name: 'Huawei Y9s',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.59,
    densityPPI: 391,
  },
  {
    name: 'LG G Pad 5 10.1"',
    width: 600,
    height: 960,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 10.1,
    densityPPI: 224,
  },
  {
    name: 'LG G4, G3',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 538,
  },
  {
    name: 'LG G5',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.3,
    densityPPI: 554,
  },
  {
    name: 'LG G6',
    width: 360,
    height: 720,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 564,
  },
  {
    name: 'LG G7 Fit, G7 One',
    width: 360,
    height: 780,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 563,
  },
  {
    name: 'LG G8 ThinQ',
    width: 360,
    height: 780,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 564,
  },
  {
    name: 'LG G8X ThinQ',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 403,
  },
  {
    name: 'LG K10, K11 Plus',
    width: 360,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.3,
    densityPPI: 277,
  },
  {
    name: 'LG K20 (2019)',
    width: 320,
    height: 640,
    deviceScaleFactor: 1.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.45,
    densityPPI: 197,
  },
  {
    name: 'LG K30',
    width: 360,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.3,
    densityPPI: 277,
  },
  {
    name: 'LG K40',
    width: 360,
    height: 720,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 282,
  },
  {
    name: 'LG K50',
    width: 360,
    height: 760,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.26,
    densityPPI: 269,
  },
  {
    name: 'LG K51S',
    width: 360,
    height: 800,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.55,
    densityPPI: 282,
  },
  {
    name: 'LG K61',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.53,
    densityPPI: 394,
  },
  {
    name: 'LG Nexus 5',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.95,
    densityPPI: 445,
  },
  {
    name: 'LG Stylo 4',
    width: 360,
    height: 720,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 390,
  },
  {
    name: 'LG Stylo 5',
    width: 360,
    height: 720,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 390,
  },
  {
    name: 'LG Tribute Empire',
    width: 360,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 294,
  },
  {
    name: 'LG W30',
    width: 360,
    height: 760,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.26,
    densityPPI: 269,
  },
  {
    name: 'LG Watch W7',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.2,
    densityPPI: 300,
  },
  {
    name: 'MacBook Air 13.3"',
    width: 1280,
    height: 800,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.3,
    densityPPI: 227,
  },
  {
    name: 'MacBook Pro',
    width: 1440,
    height: 900,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 15.4,
    densityPPI: 220,
  },
  {
    name: 'MacBook Pro 13.3"',
    width: 1280,
    height: 800,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.3,
    densityPPI: 227,
  },
  {
    name: 'MacBook Pro 16"',
    width: 1536,
    height: 960,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 16,
    densityPPI: 226,
  },
  {
    name: 'Microsoft Lumia 1020',
    width: 320,
    height: 480,
    deviceScaleFactor: 2.4,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.5,
    densityPPI: 332,
  },
  {
    name: 'Microsoft Lumia 1520',
    width: 432,
    height: 768,
    deviceScaleFactor: 2.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 367,
  },
  {
    name: 'Microsoft Lumia 520',
    width: 320,
    height: 480,
    deviceScaleFactor: 1.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 233,
  },
  {
    name: 'Microsoft Lumia 650',
    width: 360,
    height: 640,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 297,
  },
  {
    name: 'Microsoft Lumia 925',
    width: 320,
    height: 480,
    deviceScaleFactor: 2.4,
    isMobile: true,
    hasTouch: true,
    screenSize: 4.5,
    densityPPI: 332,
  },
  {
    name: 'Microsoft Lumia 950 XL',
    width: 411,
    height: 731,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 518,
  },
  {
    name: 'Microsoft Surface',
    width: 1366,
    height: 768,
    deviceScaleFactor: 1,
    isMobile: false,
    hasTouch: false,
    screenSize: 10.6,
    densityPPI: 148,
  },
  {
    name: 'Microsoft Surface 2',
    width: 1280,
    height: 720,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 10.6,
    densityPPI: 208,
  },
  {
    name: 'Microsoft Surface 3',
    width: 1280,
    height: 720,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 10.8,
    densityPPI: 204,
  },
  {
    name: 'Microsoft Surface Book',
    width: 1500,
    height: 1000,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.5,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Book 3 (13.5")',
    width: 1500,
    height: 1000,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.5,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Book 3 (15")',
    width: 1620,
    height: 1080,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 15,
    densityPPI: 260,
  },
  {
    name: 'Microsoft Surface Laptop',
    width: 1504,
    height: 1003,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.5,
    densityPPI: 201,
  },
  {
    name: 'Microsoft Surface Laptop 3 (13.5")',
    width: 1504,
    height: 1003,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 13.5,
    densityPPI: 201,
  },
  {
    name: 'Microsoft Surface Laptop 3 (15")',
    width: 1664,
    height: 1110,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 15,
    densityPPI: 201,
  },
  {
    name: 'Microsoft Surface Pro',
    width: 1280,
    height: 720,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 10.6,
    densityPPI: 208,
  },
  {
    name: 'Microsoft Surface Pro 2',
    width: 1280,
    height: 720,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 10.6,
    densityPPI: 208,
  },
  {
    name: 'Microsoft Surface Pro 3',
    width: 1440,
    height: 960,
    deviceScaleFactor: 1.5,
    isMobile: false,
    hasTouch: false,
    screenSize: 12,
    densityPPI: 216,
  },
  {
    name: 'Microsoft Surface Pro 4',
    width: 1368,
    height: 912,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 12.3,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Pro 5',
    width: 1368,
    height: 912,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 12.3,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Pro 6',
    width: 1368,
    height: 912,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 12.3,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Pro 7',
    width: 1368,
    height: 912,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 12.3,
    densityPPI: 267,
  },
  {
    name: 'Microsoft Surface Pro X',
    width: 1440,
    height: 960,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    screenSize: 13,
    densityPPI: 267,
  },
  {
    name: 'Motorola Moto G8',
    width: 360,
    height: 780,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 268,
  },
  {
    name: 'Motorola Nexus 6',
    width: 411,
    height: 731,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.96,
    densityPPI: 493,
  },
  {
    name: 'Motorola Nexus 6P',
    width: 411,
    height: 731,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 518,
  },
  {
    name: 'OnePlus 6',
    width: 412,
    height: 869,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 4,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 6T',
    width: 412,
    height: 892,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.41,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 7',
    width: 412,
    height: 892,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.41,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 7 Pro',
    width: 412,
    height: 892,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 516,
  },
  {
    name: 'OnePlus 7T',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.55,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 7T Pro',
    width: 412,
    height: 892,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 516,
  },
  {
    name: 'OnePlus 8',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.55,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 8 Pro',
    width: 412,
    height: 906,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.78,
    densityPPI: 513,
  },
  {
    name: 'OnePlus 8T',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.55,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 9',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.55,
    densityPPI: 402,
  },
  {
    name: 'OnePlus 9 Pro',
    width: 412,
    height: 919,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 525,
  },
  {
    name: 'OnePlus Nord',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.44,
    densityPPI: 408,
  },
  {
    name: 'Realme Watch 2020',
    width: 160,
    height: 160,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.4,
    densityPPI: 323,
  },
  {
    name: 'Samsung A30',
    width: 412,
    height: 892,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 403,
  },
  {
    name: 'Samsung A31',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 411,
  },
  {
    name: 'Samsung A32/td>',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 411,
  },
  {
    name: 'Samsung A50',
    width: 412,
    height: 892,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 403,
  },
  {
    name: 'Samsung A50s',
    width: 412,
    height: 892,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 403,
  },
  {
    name: 'Samsung A51',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 405,
  },
  {
    name: 'Samsung A6s',
    width: 360,
    height: 720,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 402,
  },
  {
    name: 'Samsung A70s',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 393,
  },
  {
    name: 'Samsung A71',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 393,
  },
  {
    name: 'Samsung Fold',
    width: 768,
    height: 1076,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 7.3,
    densityPPI: 362,
  },
  {
    name: 'Samsung J7 Prime2',
    width: 412,
    height: 732,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 401,
  },
  {
    name: 'Samsung Note 3',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 386,
  },
  {
    name: 'Samsung Note 4',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.7,
    densityPPI: 518,
  },
  {
    name: 'Samsung Note 8',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 521,
  },
  {
    name: 'Samsung Note 9',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 516,
  },
  {
    name: 'Samsung Note10',
    width: 412,
    height: 869,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 401,
  },
  {
    name: 'Samsung Note10+',
    width: 412,
    height: 869,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.8,
    densityPPI: 498,
  },
  {
    name: 'Samsung Note20',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 393,
  },
  {
    name: 'Samsung Note20 Ultra',
    width: 412,
    height: 883,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.9,
    densityPPI: 496,
  },
  {
    name: 'Samsung S10',
    width: 360,
    height: 760,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 550,
  },
  {
    name: 'Samsung S10 Lite',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 394,
  },
  {
    name: 'Samsung S10+',
    width: 412,
    height: 869,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 522,
  },
  {
    name: 'Samsung S20',
    width: 360,
    height: 800,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 563,
  },
  {
    name: 'Samsung S20 FE',
    width: 412,
    height: 914,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 407,
  },
  {
    name: 'Samsung S20 Ultra',
    width: 412,
    height: 915,
    deviceScaleFactor: 3.5,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.9,
    densityPPI: 511,
  },
  {
    name: 'Samsung S20+',
    width: 384,
    height: 854,
    deviceScaleFactor: 3.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 525,
  },
  {
    name: 'Samsung S21 Ultra 5G',
    width: 384,
    height: 854,
    deviceScaleFactor: 3.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.8,
    densityPPI: 515,
  },
  {
    name: 'Samsung S23 (2023)',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 425,
  },
  {
    name: 'Samsung S24 (2024)',
    width: 360,
    height: 780,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 416,
  },
  {
    name: 'Samsung S6',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.1,
    densityPPI: 577,
  },
  {
    name: 'Samsung S6 edge',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.1,
    densityPPI: 577,
  },
  {
    name: 'Samsung S7',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.1,
    densityPPI: 577,
  },
  {
    name: 'Samsung S7 Edge',
    width: 360,
    height: 640,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 534,
  },
  {
    name: 'Samsung S8',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.8,
    densityPPI: 570,
  },
  {
    name: 'Samsung S8+',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 529,
  },
  {
    name: 'Samsung S9',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.8,
    densityPPI: 570,
  },
  {
    name: 'Samsung S9+',
    width: 360,
    height: 740,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 529,
  },
  {
    name: 'Samsung Watch 1.2" (42MM)',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.2,
    densityPPI: 278,
  },
  {
    name: 'Samsung Watch 1.3" (46MM)',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.3,
    densityPPI: 278,
  },
  {
    name: 'Samsung Watch 3 1.2" (41MM) - 2020',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.2,
    densityPPI: 364,
  },
  {
    name: 'Samsung Watch 3 1.4" (45MM) - 2020',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.4,
    densityPPI: 364,
  },
  {
    name: 'Samsung Watch Active 1.2" (40MM) - 2019',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.2,
    densityPPI: 364,
  },
  {
    name: 'Samsung Watch Active 1.4" (44MM) - 2019',
    width: 180,
    height: 180,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.4,
    densityPPI: 364,
  },
  {
    name: 'Samsung Z Flip',
    width: 412,
    height: 1004,
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.7,
    densityPPI: 425,
  },
  {
    name: 'Samsung Z Fold2',
    width: 884,
    height: 1104,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 7.6,
    densityPPI: 373,
  },
  {
    name: 'Sony Xperia 1',
    width: 411,
    height: 960,
    deviceScaleFactor: 4,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 643,
  },
  {
    name: 'Sony Xperia 10',
    width: 360,
    height: 840,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6,
    densityPPI: 457,
  },
  {
    name: 'Sony Xperia 10 Plus',
    width: 360,
    height: 840,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.5,
    densityPPI: 422,
  },
  {
    name: 'Sony Xperia 5',
    width: 360,
    height: 840,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.1,
    densityPPI: 449,
  },
  {
    name: 'Sony Xperia C4',
    width: 540,
    height: 960,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.5,
    densityPPI: 401,
  },
  {
    name: 'Sony Xperia L4',
    width: 360,
    height: 840,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.2,
    densityPPI: 295,
  },
  {
    name: 'Sony Xperia X',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'Sony Xperia XZ',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 424,
  },
  {
    name: 'Sony Xperia Z Ultra',
    width: 540,
    height: 960,
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.4,
    densityPPI: 344,
  },
  {
    name: 'Sony Xperia Z2 / Z3',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 424,
  },
  {
    name: 'Sony Xperia Z3',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 424,
  },
  {
    name: 'Sony Xperia Z5',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.2,
    densityPPI: 428,
  },
  {
    name: 'vivo Y20',
    width: 385,
    height: 854,
    deviceScaleFactor: 1.875,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.51,
    densityPPI: 270,
  },
  {
    name: 'Xiaomi Mi 10',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 386,
  },
  {
    name: 'Xiaomi Mi 10 Pro',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 386,
  },
  {
    name: 'Xiaomi Mi 10T, Xiaomi Mi 10T Pro',
    width: 393,
    height: 873,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 395,
  },
  {
    name: 'Xiaomi Mi 3',
    width: 360,
    height: 640,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    screenSize: 5,
    densityPPI: 441,
  },
  {
    name: 'Xiaomi Mi 6',
    width: 393,
    height: 816,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.88,
    densityPPI: 423,
  },
  {
    name: 'Xiaomi Mi 8 SE',
    width: 393,
    height: 816,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.88,
    densityPPI: 423,
  },
  {
    name: 'Xiaomi Mi 8, Mi 8 Pro',
    width: 393,
    height: 817,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.21,
    densityPPI: 402,
  },
  {
    name: 'Xiaomi Mi 9 Lite',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.39,
    densityPPI: 403,
  },
  {
    name: 'Xiaomi Mi 9 SE',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 5.97,
    densityPPI: 432,
  },
  {
    name: 'Xiaomi Mi 9, Mi 9T',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.39,
    densityPPI: 403,
  },
  {
    name: 'Xiaomi Mi Watch 2020',
    width: 227,
    height: 227,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.39,
    densityPPI: 326,
  },
  {
    name: 'Xiaomi Mi Watch Revolve 2020',
    width: 227,
    height: 227,
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: true,
    screenSize: 1.39,
    densityPPI: 326,
  },
  {
    name: 'Xiaomi Redmi Note 7',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 409,
  },
  {
    name: 'Xiaomi Redmi Note 8',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.3,
    densityPPI: 409,
  },
  {
    name: 'Xiaomi Redmi Note 8 Pro',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.53,
    densityPPI: 395,
  },
  {
    name: 'Xiaomi Redmi Note 9',
    width: 393,
    height: 851,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.53,
    densityPPI: 395,
  },
  {
    name: 'Xiaomi Redmi Note 9 Pro',
    width: 393,
    height: 873,
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    screenSize: 6.67,
    densityPPI: 395,
  },
];
